In [1]:
import numpy as np

In [3]:
np_result1 = np.array([5,4,3,5,2])
print(type(np_result1))

<class 'numpy.ndarray'>


In [8]:
np_2d = np.array([[5,4,3,5,7],[2,5,4,5,6]])
print(np_2d)
np_2d.shape

[[5 4 3 5 7]
 [2 5 4 5 6]]


(2, 5)

In [9]:
#индексы и слайсинг
print(np_2d[0][4])
print(np_2d[0,4])
print(np_2d[:,1:3])
print(np_2d[0,:])

7
7
[[4 3]
 [5 4]]
[5 4 3 5 7]


In [26]:
height = [1.6, 1.82, 1.57, 1.72, 1.69]
weight = [74, 94, 42, 102, 62]
np_2d = np.array([height,weight])
print(np_2d)

row_2_elements = np_2d[1, :]
print("row 2:", row_2_elements)

column_3_elements = np_2d[:, 2]
print("column 3:", column_3_elements)

center_elements = np_2d[:, len(height) // 2]
print("center:", center_elements)

[[  1.6    1.82   1.57   1.72   1.69]
 [ 74.    94.    42.   102.    62.  ]]
row 2: [ 74.  94.  42. 102.  62.]
column 3: [ 1.57 42.  ]
center: [ 1.57 42.  ]
