In [1]:
import numpy as np

In [2]:
np_basketball = np.array([180, 215, 210, 210, 188, 176, 209, 200])
print(type(np_basketball))

<class 'numpy.ndarray'>


In [4]:
np_height_in = np.array([79, 74, 72, 75, 75, 73])
np_height_m = np_height_in * 0.0254
print(np_height_m)

[2.0066 1.8796 1.8288 1.905  1.905  1.8542]


In [7]:
weight_lb = np.array([180, 215, 210, 205, 190, 195])
np_weight_kg = weight_lb* 0.453592
print(np_weight_kg)

[81.64656 97.52228 95.25432 92.98636 86.18248 88.45044]


In [11]:
bmi = np_weight_kg / np_height_m**2
under_21 = bmi < 21
print(bmi)
print(under_21)

[20.2775871  27.60406069 28.48080465 25.62295933 23.74810865 25.72686361]
[ True False False False False False]


In [25]:
basketball = [[180, 78.4],[215, 102.7],[210, 98.5],[188, 75.2]]
np_basketball = np.array(basketball)

# massive type
print(type(np_basketball))

# massive shape
print(np_basketball.shape)

# print third row
print(np_basketball[2, :])

# print second column
print(np_basketball[:, 1])

# wieght all players
print(np_basketball[:, 0])

# massive coefficient
conversion = np.array([0.453592, 0.0254])

# convert all players values into kg and meters
np_basketball_kg_m = np_basketball * conversion
print(np_basketball_kg_m)

<class 'numpy.ndarray'>
(4, 2)
[210.   98.5]
[ 78.4 102.7  98.5  75.2]
[180. 215. 210. 188.]
[[81.64656   1.99136 ]
 [97.52228   2.60858 ]
 [95.25432   2.5019  ]
 [85.275296  1.91008 ]]
