In [2]:
import numpy as np

In [4]:
#Недостотаток Lists
np_result1 = np.array([5,4,3,5,2])
np_result2 = np.array([4,5,2,5,5])

avg_result = (np_result1 + np_result2)/2
print(avg_result)

[4.5 4.5 2.5 5.  3.5]


In [7]:
#arrays должны содержать один тип данных
np_result1 = np.array([5,4,3,5,2])
print(np_result1**2)

np_result2 = np.array([4,5,2,5,5])

avg_result = (np_result1 + np_result2)/2
print(avg_result)

[25 16  9 25  4]
[4.5 4.5 2.5 5.  3.5]


In [8]:
#сложение lists verse arrays
result1 = [5,4,3,5,2]
result2 = [4,5,2,5,5]
print(result1 + result2)

np_result1 = np.array([5,4,3,5,2])
np_result2 = np.array([4,5,2,5,5])
print(np_result1 + np_result2)

[5, 4, 3, 5, 2, 4, 5, 2, 5, 5]
[ 9  9  5 10  7]


In [9]:
#lists verse Arrays
np_result1 = np.array([5,4,3,5,2])
print(np_result1[1])
print(np_result1 > 3)
print(np_result1[np_result1 > 3])

4
[ True  True False  True False]
[5 4 5]


In [19]:
height = np.array([1.6, 1.82, 1.57, 1.72, 1.69])
weight = np.array([74, 94, 42, 102, 62])

bmi = weight / height ** 2
print(bmi)

[28.90625    28.37821519 17.0392308  34.47809627 21.70792339]


In [26]:
#расчет нормы
height = np.array([1.6, 1.82, 1.57, 1.72, 1.69])
weight = np.array([74, 94, 42, 102, 62])

bmi = weight / height ** 2

for i in range(len(height)):
    current_bmi = bmi[i]

    if current_bmi > 25:
        print(current_bmi)
    elif current_bmi < 18.5:
        print(current_bmi)
    else:
        print(current_bmi)

28.906249999999993
28.378215191402003
17.03923080043815
34.47809626825311
21.707923392038097


In [3]:
np_result1 = np.array([5,4,3,5,2])
print(type(np_result1))

<class 'numpy.ndarray'>
